<template>
  <v-toolbar 
    color="white" 
    flat 
    absolute 
    app>
    <div>
      <div>
        <img 
          class="logo" 
          src="../assets/spacelab-logo.svg">
      </div>
    </div>
  </v-toolbar>
</template>
<script>
</script>
